[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "unicodedata-parser"
version = "0.1.0"
description = ""
authors = ["Koji Ishii <kojii@chromium.org>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"
pytest = "^6.2.4"
tox = "^3.24.1"

[tool.pytest.ini_options]
testpaths = "tests"
